package cmd

import (
	"fmt"
	"os"
	"runtime"
	"strings"

	"github.com/spf13/cobra"
)

var shellInitShell string

var shellInitCmd = &cobra.Command{
	Use:   "shell-init",
	Short: "Output shell integration script for auto-cd on new/switch",
	Long: `Output a shell wrapper function that makes 'focus new' and 'focus switch'
automatically cd into the workspace on success.

Add to your shell config:
  bash/zsh:  eval "$(focus shell-init)"
  fish:      focus shell-init | source`,
	// Override parent PersistentPreRunE — shell-init is pure stdout, no repo needed.
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error { return nil },
	RunE: func(cmd *cobra.Command, args []string) error {
		sh := shellInitShell
		if sh == "" {
			sh = detectShell()
		}
		switch sh {
		case "fish":
			fmt.Print(fishScript)
		case "pwsh", "powershell":
			fmt.Print(pwshScript)
		default:
			fmt.Print(bashZshScript)
		}
		return nil
	},
}

func init() {
	shellInitCmd.Flags().StringVar(&shellInitShell, "shell", "", "shell type: bash, zsh, fish, pwsh (auto-detected if omitted)")
	rootCmd.AddCommand(shellInitCmd)
}

func detectShell() string {
	shell := os.Getenv("SHELL")
	switch {
	case strings.HasSuffix(shell, "fish"):
		return "fish"
	case strings.HasSuffix(shell, "zsh"):
		return "zsh"
	case strings.HasSuffix(shell, "bash"):
		return "bash"
	default:
		if runtime.GOOS == "windows" {
			return "pwsh"
		}
		return "bash"
	}
}

const bashZshScript = `# focus shell integration — generated by: focus shell-init
# Add to ~/.bashrc or ~/.zshrc:  eval "$(focus shell-init)"
focus() {
  command focus "$@"
  local ret=$?
  if [ $ret -eq 0 ] && { [ "$1" = "new" ] || [ "$1" = "switch" ]; }; then
    local ws
    ws=$(command focus workspace "${@: -1}" 2>/dev/null)
    [ -n "$ws" ] && cd "$ws"
  fi
  return $ret
}
`

const fishScript = `# focus shell integration — generated by: focus shell-init
# Add to ~/.config/fish/config.fish:  focus shell-init | source
function focus
  command focus $argv
  set ret $status
  if test $ret -eq 0; and contains -- $argv[1] new switch
    set ws (command focus workspace $argv[-1] 2>/dev/null)
    and cd $ws
  end
  return $ret
end
`

const pwshScript = `# focus shell integration — generated by: focus shell-init
# Add to $PROFILE:  Invoke-Expression (focus shell-init --shell pwsh)
function Invoke-Focus {
  $focusBin = (Get-Command focus -CommandType Application | Select-Object -First 1).Source
  & $focusBin @args
  if ($LASTEXITCODE -eq 0 -and ($args[0] -eq 'new' -or $args[0] -eq 'switch')) {
    $ws = & $focusBin workspace $args[-1] 2>$null
    if ($ws) { Set-Location $ws }
  }
}
Set-Alias focus Invoke-Focus
`
